### ISSUE TITLE
Improve user addition experience

### ISSUE THREAD

**Issue by lramirezsuarez** [PinkPork/mafia#51]
# Improve User Addition Experience
## Description
The current alert to add an user has many steps to be able to add a player, we could use an empty list at the end to add a new name or improve the alert to automatically enable the Add button as soon as more than 2 characters are introduced

## Acceptance Criteria
- Alert to add an user without that many steps
- Additional way to add a player without the alert?

## Observations
- Migrate to SwiftUI?

**Comment by santicarmo31** [comment]
#57
